namespace: kube-system

resources:
  - ../../base

configMapGenerator:
  - files:
      - values.yaml
    name: metrics-server-values
    options:
      disableNameSuffixHash: true
      labels:
        helm.toolkit.fluxcd.io/watch: "true"
