args:
  - --kubelet-preferred-address-types=InternalIP
  - --metric-resolution=15s
  - --kubelet-insecure-tls=true
apiService:
  insecureSkipTLSVerify: false
extraArgs:
  - --kubelet-use-node-status-port
tls:
  type: cert-manager
