apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hf-token-secret-external
  namespace: llm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: hf-token-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: hf-token-secret
