apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
spec:
  storageClassName: nfs-csi-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
