#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - vim
  - tmux
  - haproxy
  - keepalived

write_files:
  - path: /etc/haproxy/haproxy.cfg
    content: |
      frontend k3s-frontend
        bind *:6443
        mode tcp
        option tcplog
        default_backend k3s-backend

      backend k3s-backend
        mode tcp
        option tcp-check
        default-server inter 10s downinter 5s
        balance roundrobin

  - path: /etc/keepalived/keepalived.conf
    content: |
      global_defs {
        enable_script_security
        script_user root
      }

      vrrp_script chk_haproxy {
          script "killall -0 haproxy"
          interval 2
      }

      vrrp_instance haproxy-vip {
          interface enp0s2
          state MASTER
          priority 200
          virtual_router_id 51

          virtual_ipaddress {
              192.168.1.250/24
          }

          track_script {
              chk_haproxy
          }
      }

runcmd:
  - systemctl enable haproxy
  - systemctl enable keepalived
  - systemctl start haproxy
  - systemctl start keepalived
