apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp
spec:
  selector:
    matchLabels:
      name: llama-cpp
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: llama-cpp
    spec:
      runtimeClassName: nvidia
      initContainers:
        - name: download-model
          image: python:3.14-slim@sha256:bc389f7dfcb21413e72a28f491985326994795e34d2b86c8ae2f417b4e7818aa
          command:
            - sh
            - -c
            - |
              apt-get update -qq && \
              apt-get install -y --no-install-recommends curl git && \
              pip install -U huggingface_hub[hf_transfer] hf_transfer && \
              export HF_HUB_ENABLE_HF_TRANSFER=1 && \
              mkdir -p /models && \
              hf download \
                unsloth/Qwen3.6-35B-A3B-GGUF Qwen3.6-35B-A3B-UD-IQ2_M.gguf \
                --local-dir /models
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-secret
                  key: token
          volumeMounts:
            - name: model-storage
              mountPath: /models
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1
              memory: 4Gi
      containers:
        - name: llama-cpp
          image: ghcr.io/ggml-org/llama.cpp:server-cuda@sha256:9f2e2b23e5b42b683801e2f0847ed5dfd68c9da3da7a46e09d49dea907c58b67
          args:
            - -m
            - /models/Qwen3.6-35B-A3B-UD-IQ2_M.GGUF
            - --host
            - 0.0.0.0
            - --port
            - "8080"
            - -c
            - "131072"
            - -np
            - "1"
            - -ngl
            - "99"
            - --temp
            - "0.7"
            - --top-p
            - "0.8"
            - --top-k
            - "20"
            - --presence_penalty
            - "1.5"
            - --min-p
            - "0.00"
            - --alias
            - "unsloth/qwen3.6"
            - --chat-template-kwargs
            - '{"enable_thinking":false}'

          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: model-storage
              mountPath: /models
          resources:
            limits:
              cpu: "4"
              memory: 16G
              nvidia.com/gpu: "1"
            requests:
              cpu: "2"
              memory: 4G
              nvidia.com/gpu: "1"
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: llm-model-cache-pvc
