apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp
spec:
  selector:
    matchLabels:
      name: llama-cpp
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: llama-cpp
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        nvidia.com/gpu.present: "true"
      initContainers:
        - name: download-model
          image: python:3.14-slim@sha256:ce40764625a4ff50df3548277632e7f96c4e77fe75fa848aae9885476e7df5a4
          command:
            - sh
            - -c
            - |
              apt-get update -qq && \
              apt-get install -y --no-install-recommends curl git && \
              pip install -U huggingface_hub[hf_transfer] hf_transfer && \
              export HF_HUB_ENABLE_HF_TRANSFER=1 && \
              mkdir -p /models && \
              hf download \
                unsloth/Qwen3.8-27B-GGUF Qwen3.8-27B-UD-Q3_K_XL.gguf \
                --local-dir /models
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token-secret
                  key: token
          volumeMounts:
            - name: model-storage
              mountPath: /models
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 1
              memory: 4Gi
      containers:
        - name: llama-cpp
          image: ghcr.io/ggml-org/llama.cpp:server-cuda@sha256:952424b09abc18668a9891041b275bf8c96afb6107d65d33ba104da9b18490c7
          args:
            - -m
            - /models/Qwen3.8-27B-UD-Q3_K_XL.gguf
            - --host
            - 0.0.0.0
            - --port
            - "8080"
            - -c
            - "65536"
            - -np
            - "1"
            - --spec-type
            - draft-mtp
            - --spec-draft-n-max
            - "4"
            - -fa
            - "1"
            - --cache-type-k
            - q4_0
            - --cache-type-v
            - q4_0
            - -ngl
            - "99"
            - --temp
            - "0.7"
            - --top-p
            - "0.8"
            - --top-k
            - "20"
            - --presence_penalty
            - "1.5"
            - --min-p
            - "0.00"
            - --alias
            - "unsloth/qwen3.8"
            - --chat-template-kwargs
            - '{"enable_thinking":false}'

          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: model-storage
              mountPath: /models
          resources:
            limits:
              cpu: "4"
              memory: 16G
              nvidia.com/gpu: "1"
            requests:
              cpu: "2"
              memory: 4G
              nvidia.com/gpu: "1"
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: llm-model-cache-pvc
