namespace: flux-system

resources:
  - webdav.yaml
  - itzg.yaml
  - jetstack.yaml
  - vmware-tanzu.yaml
  - external-secrets.yaml
  - nvidia.yaml
  - uptime-kuma.yaml
  - coder-v2.yaml
  - immich-app.yaml
  - harbor.yaml
  - kyverno.yaml
  - metrics-server.yaml
  - rancher-stable.yaml
  - traefik.yaml
  - grafana.yaml
  - grafana-community.yaml
  - prometheus-community.yaml
