apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: navidrome-secrets-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: navidrome-secrets
    creationPolicy: Owner
  data:
    - secretKey: ND_LASTFM_APIKEY
      remoteRef:
        key: nd-lastfm-apikey
    - secretKey: ND_LASTFM_SECRET
      remoteRef:
        key: nd-lastfm-secret
