apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm:main-v1.75.5-stable
          ports:
            - containerPort: 4000
          args:
            - --config
            - /app/config.yaml
          volumeMounts:
            - name: litellm-config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
          env:
            - name: LITELLM_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: litellm-secrets
                  key: primary-key
            - name: LITELLM_SALT_KEY
              valueFrom:
                secretKeyRef:
                  name: litellm-secrets
                  key: salt
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: litellm-secrets
                  key: db-url
            - name: STORE_MODEL_IN_DB
              value: "True"
      volumes:
        - name: litellm-config-volume
          configMap:
            name: litellm-config
