#!/bin/bash
CLUSTER_NAME="homelab"

SERVER_COUNT="0"
SERVER_CPU="2"
SERVER_MEM="2G"
SERVER_DISK="20G"

AGENT_COUNT="1"
AGENT_CPU="1"
AGENT_MEM="1G"
AGENT_DISK="20G"

LOAD_BALANCER_COUNT="0"
LOAD_BALANCER_CPU="1"
LOAD_BALANCER_MEM="1G"
LOAD_BALANCER_DISK="10G"
