#!/bin/bash
K3S_CONFIG_DIR="$HOME/.kube/k3s"

CLUSTER_NAME="homelab"
K3S_TOKEN_DIR=$K3S_CONFIG_DIR/$CLUSTER_NAME-token.txt

SERVER_COUNT="1"
SERVER_CPU="2"
SERVER_MEM="2G"
SERVER_DISK="20G"

AGENT_COUNT="0"
AGENT_CPU="1"
AGENT_MEM="1G"
AGENT_DISK="20G"
