prometheus:
  prometheusSpec:
    retention: 30d
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

grafana:
  enabled: true
  persistence:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 1Gi
