prometheus:
  prometheusSpec:
    retention: 14d
    retentionSize: 100GB
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 150Gi
    podMonitorSelector:
      matchLabels:
        prometheus: kube-prometheus-stack-prometheus

grafana:
  enabled: true
  persistence:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 1Gi
