gitea:
  additionalConfigFromEnvs:
    - name: FORGEJO__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: forgejo-db-credentials
          key: password
    - name: FORGEJO__DATABASE__USER
      valueFrom:
        secretKeyRef:
          name: forgejo-db-credentials
          key: username
  config:
    database:
      DB_TYPE: postgres
      HOST: forgejo-db-rw:5432
      NAME: forgejo
    server:
      ROOT_URL: https://git.leehosanganson.dev
      DOMAIN: git.leehosanganson.dev
      SSH_DOMAIN: git.leehosanganson.dev
      SSH_PORT: 2222
      SSH_LISTEN_PORT: 2222

service:
  ssh:
    port: 2222

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
  hosts:
    - host: git.leehosanganson.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: forgejo-tls
      hosts:
        - git.leehosanganson.dev

persistence:
  enabled: true
  claimName: forgejo-pvc
