apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-media-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.197
  share: /volume1/media
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - hard
  - nfsvers=4.1

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-media-csi-retain
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.197
  share: /volume1/media
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - hard
  - nfsvers=4.1
