apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
parameters:
  fsType: "btrfs"
  dsm: "nas1.home.lab"
  location: "/volume1"
  formatOptions: "--nodiscard"
reclaimPolicy: Retain
allowVolumeExpansion: true
