apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-default
provisioner: csi.san.synology.com
parameters:
  fsType: "btrfs"
  dsm: "nas1.home.lab"
  location: "/volume1"
  formatOptions: "--nodiscard"
reclaimPolicy: Delete
allowVolumeExpansion: true
