apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: life-in-the-uk-quiz-secrets-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: life-in-the-uk-quiz-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: life-in-the-uk-quiz-db-username
    - secretKey: password
      remoteRef:
        key: life-in-the-uk-quiz-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: life-in-the-uk-quiz-db-url-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: life-in-the-uk-quiz-db-url
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: life-in-the-uk-quiz-db-url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: life-in-the-uk-quiz-backup-env-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: life-in-the-uk-quiz-backup-env
    creationPolicy: Owner
  data:
    - secretKey: storage-account-name
      remoteRef:
        key: homelab-backup-storageaccount-name
    - secretKey: blob-sas
      remoteRef:
        key: life-in-the-uk-quiz-blob-sas
