apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-qr
spec:
  selector:
    matchLabels:
      app: mini-qr
  replicas: 1
  template:
    metadata:
      labels:
        app: mini-qr
    spec:
      containers:
        - name: mini-qr
          image: ghcr.io/lyqht/mini-qr:v0.30.1@sha256:1d359c8e562e04440af934d43793270aadf21a2306b7c02139f01c216229ce03
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: "128Mi"
              cpu: "500m"
