apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-qr
spec:
  selector:
    matchLabels:
      app: mini-qr
  replicas: 1
  template:
    metadata:
      labels:
        app: mini-qr
    spec:
      containers:
        - name: mini-qr
          image: ghcr.io/lyqht/mini-qr:v0.30.2@sha256:616e30968a1e9e9f0c1a566364722e9140041f2748c83f6331399b6d105ab160
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: "128Mi"
              cpu: "500m"
