apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-qr
spec:
  selector:
    matchLabels:
      app: mini-qr
  replicas: 1
  template:
    metadata:
      labels:
        app: mini-qr
    spec:
      containers:
        - name: mini-qr
          image: ghcr.io/lyqht/mini-qr:v0.31.0@sha256:b4d946254c8c724b0022d88dacd61765f6371fb69ebc6f09b77bc2b71c4a6494
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: "128Mi"
              cpu: "500m"
