apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmp
  namespace: ...
spec:
  storageClassName: "nfs-csi-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: data-migrator
  namespace: ...
spec:
  containers:
    - name: migrator
      image: harbor.leehosanganson.dev/dockerhub/library/alpine
      command: ["sh", "-c", "cp -av /source/. /destination/ && sleep infinity"]
      volumeMounts:
        - name: source
          mountPath: /source
        - name: destination
          mountPath: /destination
  volumes:
    - name: source
      persistentVolumeClaim:
        claimName: ...
    - name: destination
      persistentVolumeClaim:
        claimName: tmp
