apiVersion: v1
kind: PersistentVolume
metadata:
  name: actual-budget-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/rancher/k3s/storage/actual-budget-pv"
  storageClassName: local-path
