apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-pvc
  namespace: actual-budget
spec:
  storageClassName: nfs-csi-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
