tunnel: 0b6d7ce8-ec69-4f2b-8410-67a378342284
credentials-file: /etc/cloudflared/creds/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true

ingress:
  - hostname: leehosanganson.dev
    service: http://traefik.kube-system:80
  - hostname: "*.leehosanganson.dev"
    service: http://traefik.kube-system:80
  - service: http_status:404
