namespace: cloudflare
resources:
  - namespace.yaml
  - ../../base
  - secrets.yaml

configMapGenerator:
  - files:
      - config.yaml
    name: cloudflared-config
    options:
      disableNameSuffixHash: true

