apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    home.lab:53 {
      forward . 192.168.1.1  # Replace with your local DNS server IP
    }
