apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-db-env-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: coder-db-env
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: coder-db-username
    - secretKey: password
      remoteRef:
        key: coder-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-db-url-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: coder-db-url
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: coder-db-url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-backup-env-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: coder-backup-env
    creationPolicy: Owner
  data:
    - secretKey: storage-account-name
      remoteRef:
        key: homelab-backup-storageaccount-name
    - secretKey: blob-sas
      remoteRef:
        key: coder-blob-sas
