apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  VITE_BACKEND_HOST: https://life-in-the-uk-quiz.leehosanganson.dev/api
  CONTACT_EMAIL: "leehosanganson@gmail.com"
  OPERATOR_NAME: "Ho Sang Lee"
  POLICY_UPDATE_DATE: "5 April 2026"
  GITHUB_URL: https://github.com/leehosanganson/life-in-the-uk-quiz
  APP_VERSION: v0.0.4
