apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: life-in-the-uk-quiz-frontend
  template:
    metadata:
      labels:
        app: life-in-the-uk-quiz-frontend
    spec:
      containers:
        - name: frontend
          image: harbor.leehosanganson.dev/leehosanganson/life-in-the-uk-quiz-frontend:v0.0.4@sha256:4d0ca6c2831b9dd1bf2a6cc9991dd1f8436df9cd1da413eaa0be29e589b8f153
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: frontend-config
      restartPolicy: Always
