apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
spec:
  interval: 1h
  chart:
    spec:
      chart: ./script/helm/garage
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: garage-values
