apiVersion: apps/v1
kind: Deployment
metadata:
  name: soularr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soularr
  template:
    metadata:
      labels:
        app: soularr
    spec:
      nodeSelector:
        stack.arr: "arr-1"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      dnsPolicy: ClusterFirst
      containers:
        - name: soularr
          image: mrusse08/soularr:latest
          env:
            - name: TZ
              value: "Etc/UTC"
            - name: SCRIPT_INTERVAL
              value: "300"
          volumeMounts:
            - name: config
              mountPath: /data
            - name: downloads
              mountPath: /downloads
              subPath: music
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: soularr-pvc
        - name: downloads
          persistentVolumeClaim:
            claimName: qbit-download
