apiVersion: v1
kind: PersistentVolume
metadata:
  name: zotero-webdav-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/rancher/k3s/storage/zotero-webdav-pv"
  storageClassName: local-path
