apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zotero-webdav-pvc
  namespace: zotero
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: zotero-webdav-pv
