apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zotero-pvc
  namespace: zotero
spec:
  storageClassName: nfs-csi-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
