# values.yaml
urls:
  /:
    htpasswdSecretRef:
      name: webdav-htpasswd
      key: root

existingHtpasswdSecrets:
  - name: webdav-htpasswd

ingress:
  enabled: true
  className: traefik
  host: zotero.leehosanganson.dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare

persistence:
  enabled: true
  existingClaim: zotero-webdav-pvc

namespace: zotero
