apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: life-in-the-uk-quiz-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: life-in-the-uk-quiz-backend
    spec:
      containers:
        - name: backend
          image: harbor.leehosanganson.dev/leehosanganson/life-in-the-uk-quiz-backend:v0.0.3@sha256:3f69192d3fc1276d01ce995eab36bdbc09566b51bd9fc176d2d06285ab147cc4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: life-in-the-uk-quiz-db-url
                  key: database-url
      restartPolicy: Always
