apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-user
    - secretKey: admin-password
      remoteRef:
        key: grafana-password
