persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  existingClaim: pvc-89ae83eb-0c63-401b-8739-5e15a89effe7

admin:
  existingSecret: prometheus-grafana
  userKey: admin-user
  passwordKey: admin-password

plugins:
  - grafana-lokiexplore-app 1.0.37
