apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db
  labels:
    db: forgejo-db
spec:
  instances: 2
  storage:
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
      secret:
        name: forgejo-db-credentials
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: forgejo-backup-storage
  externalClusters:
    - name: clusterBackup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: forgejo-backup-storage
          serverName: forgejo-db-backup
