apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: open-webui
  name: open-webui
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      volumes:
        - name: webui-data
          persistentVolumeClaim:
            claimName: open-webui-pvc
      containers:
        - image: ghcr.io/open-webui/open-webui:v0.10.2@sha256:9fcea9c6e32ab60b0498f3986c6cdf651ddbe61db48d2213a3d28048ddd673d4
          name: open-webui
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: open-web-ui-configmap
          volumeMounts:
            - name: webui-data
              mountPath: /app/backend/data
