apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: open-webui
  name: open-webui
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      volumes:
        - name: webui-data
          persistentVolumeClaim:
            claimName: open-webui-pvc
      containers:
        - image: ghcr.io/open-webui/open-webui:v0.9.5@sha256:e045bde3b004cc7f8c319412345eb56c87ea6ac57031534a31ca37ad5424beb3
          name: open-webui
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: webui-data
              mountPath: /app/backend/data
