apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: open-webui
  name: open-webui
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      volumes:
        - name: webui-data
          persistentVolumeClaim:
            claimName: open-webui-pvc
      containers:
        - image: ghcr.io/open-webui/open-webui:v0.9.6@sha256:90eae5b419e40b4c3dd684582b2c83440b36f9ae2f6532c09639b2ba4ee65158
          name: open-webui
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: open-web-ui-configmap
          volumeMounts:
            - name: webui-data
              mountPath: /app/backend/data
