apiVersion: apps/v1
kind: Deployment
metadata:
  name: novnc-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novnc-chrome
  template:
    metadata:
      labels:
        app: novnc-chrome
    spec:
      containers:
        - name: novnc-chrome
          image: ghcr.io/gitxpresso/chromekasmvnc:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - name: chrome-profile
              mountPath: /home/kasm-user
      volumes:
        - name: chrome-profile
          persistentVolumeClaim:
            claimName: novnc-chrome-pvc
