apiVersion: apps/v1
kind: Deployment
metadata:
  name: novnc-chrome
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: novnc-chrome
  template:
    metadata:
      labels:
        app: novnc-chrome
    spec:
      runtimeClassName: nvidia
      securityContext:
        fsGroup: 1000
      containers:
        - name: novnc-chrome
          image: linuxserver/chromium:latest@sha256:be565732328d95754e45d826b3987e659b5f961fe267be88e8b1808567e94842
          securityContext:
            seccompProfile:
              type: Unconfined
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "4"
              memory: "4Gi"
          volumeMounts:
            - name: chrome-profile
              mountPath: /config
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: chrome-profile
          persistentVolumeClaim:
            claimName: novnc-chrome-pvc
        - name: dshm
          emptyDir:
            medium: Memory
