apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secrets-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: homepage-secrets
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_PROXMOX_API_TOKEN_SECRET
      remoteRef:
        key: proxmox-api-token-secret
    - secretKey: HOMEPAGE_VAR_JELLYFIN_API_KEY
      remoteRef:
        key: jellyfin-api-key
    - secretKey: HOMEPAGE_VAR_JELLYSEERR_API_KEY
      remoteRef:
        key: jellyseerr-api-key
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: sonarr-api-key
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: radarr-api-key
    - secretKey: HOMEPAGE_VAR_LIDARR_API_KEY
      remoteRef:
        key: lidarr-api-key
    - secretKey: HOMEPAGE_VAR_BAZARR_API_KEY
      remoteRef:
        key: bazarr-api-key
    - secretKey: HOMEPAGE_VAR_PROWLARR_API_KEY
      remoteRef:
        key: prowlarr-api-key
    - secretKey: HOMEPAGE_VAR_QBITTORRENT_USERNAME
      remoteRef:
        key: qbittorrent-username
    - secretKey: HOMEPAGE_VAR_QBITTORRENT_PASSWORD
      remoteRef:
        key: qbittorrent-password
    - secretKey: HOMEPAGE_VAR_UNIFI_API_KEY
      remoteRef:
        key: unifi-api-key
    - secretKey: HOMEPAGE_VAR_PIHOLE_1_API_KEY
      remoteRef:
        key: pihole-1-api-key
    - secretKey: HOMEPAGE_VAR_PIHOLE_2_API_KEY
      remoteRef:
        key: pihole-2-api-key
    - secretKey: HOMEPAGE_VAR_SYNOLOGY_USERNAME
      remoteRef:
        key: synology-username
    - secretKey: HOMEPAGE_VAR_SYNOLOGY_PASSWORD
      remoteRef:
        key: synology-password
