title: Homelab
theme: dark
color: slate
headerStyle: clean
cardBlur: md
target: _blank
hideVersion: true
useEqualHeights: true
layout:
  Main Dashboard:
    tab: Main
  DevOps & Infra:
    tab: Infra
  Monitoring & Health:
    tab: Monitoring

  Links:
    tab: Main
    style: row
    columns: 5
  Home:
    tab: Main
    style: row
    columns: 4
  Productivity:
    tab: Main
    style: row
    columns: 4
  Dev:
    tab: Main
    style: row
    columns: 4
  Entertainment:
    tab: Main
    style: row
    columns: 2
  Music:
    tab: Main
    style: row
    columns: 4
  Downloads:
    tab: Main
    style: row
    columns: 5
  AI:
    tab: Main
    style: row
    columns: 2

  Cloud:
    tab: Infra
    style: row
    columns: 3
  Networking:
    tab: Infra
    style: row
    columns: 3
  Virtual Machines:
    tab: Infra
    style: row
    columns: 3
  Infrastructure:
    tab: Infra
    style: row
    columns: 2
  Storage:
    tab: Infra
    style: row
    columns: 2

  Monitoring:
    tab: Monitoring
    style: row
    columns: 3
