apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      runtimeClassName: nvidia
      containers:
        - name: chrome
          image: linuxserver/chrome:148.0.7778@sha256:23f2b3c13e12e0d483d1c3caf05b01a8c87d351b63a24f418f74b4fc5eaec68a
          envFrom:
            - configMapRef:
                name: chrome-env
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 3001
              name: https
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "4"
              memory: "4Gi"
          volumeMounts:
            - name: chrome-profile
              mountPath: /config
            - name: dri
              mountPath: /dev/dri
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: chrome-profile
          persistentVolumeClaim:
            claimName: chrome-pvc
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: shm
          emptyDir:
            medium: Memory
