apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      runtimeClassName: nvidia
      containers:
        - name: chrome
          image: linuxserver/chrome:148.0.7778@sha256:84f5910da341cabc956191268a31083c0af430a11e167bc6a7d9194f5a21d3de
          envFrom:
            - configMapRef:
                name: chrome-env
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 3001
              name: https
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "4"
              memory: "4Gi"
          volumeMounts:
            - name: chrome-profile
              mountPath: /config
            - name: dri
              mountPath: /dev/dri
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: chrome-profile
          persistentVolumeClaim:
            claimName: chrome-pvc
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: shm
          emptyDir:
            medium: Memory
