apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        nvidia.com/gpu.present: "true"
      containers:
        - name: chrome
          image: linuxserver/chrome:152.0.7977@sha256:01593e90705a500a63b3523070a2f126d40348cdf801dda25d4c4786f3b74bbe
          envFrom:
            - configMapRef:
                name: chrome-env
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 3001
              name: https
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "4"
              memory: "4Gi"
          volumeMounts:
            - name: chrome-profile
              mountPath: /config
            - name: dri
              mountPath: /dev/dri
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: chrome-profile
          persistentVolumeClaim:
            claimName: chrome-pvc
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: shm
          emptyDir:
            medium: Memory
