apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-db
  namespace: commafeed
  labels:
    db: commafeed-db
spec:
  instances: 3
  storage:
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: commafeed
      owner: commafeed
      secret:
        name: commafeed-env
