apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: commafeed-db-2
  namespace: commafeed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-retain
