apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: commafeed-env-external
  namespace: commafeed
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: commafeed-env
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: commafeed-db-username
    - secretKey: password
      remoteRef:
        key: commafeed-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-creds-external
  namespace: commafeed
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: commafeed-backup-env
    creationPolicy: Owner
  data:
    - secretKey: connection-string
      remoteRef:
        key: homelab-backup-connection-string
    - secretKey: storage-account-name
      remoteRef:
        key: homelab-backup-storageaccount-name
    - secretKey: blob-sas
      remoteRef:
        key: commafeed-blob-sas
