apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: commafeed-env-external
  namespace: commafeed
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: commafeed-env
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: commafeed-db-username
    - secretKey: password
      remoteRef:
        key: commafeed-db-password
