apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: open-webui
  name: open-webui-pvc
  namespace: llm
spec:
  storageClassName: "nfs-csi-retain"
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
