apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-cert
  namespace: tests
spec:
  dnsNames:
    - whoami.leehosanganson.dev
  secretName: whoami-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
