apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-azure-storage-credentials-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: loki-azure-storage-credentials
    creationPolicy: Owner
  data:
    - secretKey: AZURE_STORAGE_ACCOUNT_NAME
      remoteRef:
        key: homelab-backup-storageaccount-name
    - secretKey: AZURE_STORAGE_ACCOUNT_KEY
      remoteRef:
        key: loki-storage-account-key
