namespace: renovate
resources:
  - namespace.yaml
  - secrets.yaml
  - ../../base

configMapGenerator:
  - files:
      - config.json
    name: renovate-config
    options:
      disableNameSuffixHash: true
