apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-git-private-key-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: renovate-git-private-key
    creationPolicy: Owner
  data:
    - secretKey: GIT_PRIVATE_KEY
      remoteRef:
        key: renovate-git-private-key
