resources:
  - namespace.yaml
  - ../../uptime-kuma/overlays/default
  - ../../kube-prometheus-stack/overlays/default
  - ../../loki/overlays/default
  - ../../alloy/overlays/default
  - ../../grafana/overlays/default
