resources:
  - namespace.yaml
  - ../../garage/overlays/default
  - ../../uptime-kuma/overlays/default
  - ../../prometheus/overlays/default
  - ../../loki/overlays/default
  - ../../alloy/overlays/default
  - ../../grafana/overlays/default
