apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring
spec:
  dnsNames:
    - grafana.homelab.leehosanganson.dev
  secretName: grafana-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
