apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secrets-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: harbor-secrets
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: harbor-admin-password
