apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      enableServiceLinks: false

      initContainers:
        - name: setup-config
          image: busybox@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
          command:
            - "/bin/sh"
            - "-c"
            - "cp /tmp/config/settings.yml /etc/searxng/settings.yml && chown -R 977:977 /etc/searxng"
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
            - name: searxng-config-readonly
              mountPath: /tmp/config
            - name: searxng-config-dir
              mountPath: /etc/searxng

      containers:
        - name: searxng
          image: searxng/searxng:latest@sha256:654eff5a61e7a768b233b89da64ba71904d06c67c2f43fb31ab5ce20b6f1e44c
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: searxng-config
            - secretRef:
                name: searxng-secrets
          securityContext:
            runAsNonRoot: true
            runAsUser: 977
            runAsGroup: 977
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: searxng-config-dir
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: tmp
          emptyDir: {}
        - name: searxng-config-dir
          emptyDir: {}
        - name: searxng-config-readonly
          configMap:
            name: searxng-config
