apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      enableServiceLinks: false

      initContainers:
        - name: setup-config
          image: busybox@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
          command:
            - "/bin/sh"
            - "-c"
            - "cp /tmp/config/settings.yml /etc/searxng/settings.yml && chown -R 977:977 /etc/searxng"
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
            - name: searxng-config-readonly
              mountPath: /tmp/config
            - name: searxng-config-dir
              mountPath: /etc/searxng

      containers:
        - name: searxng
          image: searxng/searxng:latest@sha256:892cf809341915a4b7710d3c9045005b4c377d51335a089b6d4da0b28750788d
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: searxng-config
            - secretRef:
                name: searxng-secrets
          securityContext:
            runAsNonRoot: true
            runAsUser: 977
            runAsGroup: 977
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: searxng-config-dir
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: 128Mi
              cpu: 50m
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: tmp
          emptyDir: {}
        - name: searxng-config-dir
          emptyDir: {}
        - name: searxng-config-readonly
          configMap:
            name: searxng-config
