apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
  namespace: utility
spec:
  selector:
    matchLabels:
      app: it-tools
  replicas: 1
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
        - name: it-tools
          image: corentinth/it-tools:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: it-tools
  namespace: utility
spec:
  selector:
    app: it-tools
  ports:
    - port: 80
      targetPort: 80
