apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-tls
spec:
  secretName: homelab-tls-secret
  dnsNames:
    - "*.homelab.leehosanganson.dev"
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
