namespace: monitoring

resources:
  - ../../base

configMapGenerator:
  - files:
      - values.yaml
    name: alloy-values
    options:
      disableNameSuffixHash: true
      labels:
        helm.toolkit.fluxcd.io/watch: "true"
