resources:
  - actual-budget.yaml
  - commafeed.yaml
  - coder.yaml
  - home-assistant.yaml
  - karakeep.yaml
  - llm.yaml
  - media.yaml
  - n8n.yaml
  - paperless.yaml
  - utility.yaml
  - zotero.yaml
  - navidrome.yaml
  - life-in-the-uk-quiz.yaml
