apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: https://lhs-kubernetes-keyvault.vault.azure.net
      tenantId: 64d56fc8-65a6-4591-9a23-5b6a47b2cf29
      authSecretRef:
        clientId:
          name: azure-sp-secret
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azure-sp-secret
          key: ClientSecret
          namespace: external-secrets
