apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kv-secret-example
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: test-k8s-secret
    creationPolicy: Owner
  data:
    - secretKey: my-secret-key # key in resulting K8s secret
      remoteRef:
        key: testKey # name in Azure Key Vault
