apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-cloudflare-api-token-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: traefik-cloudflare-api-token
    creationPolicy: Owner
  data:
    - secretKey: CF_DNS_API_TOKEN
      remoteRef:
        key: cloudflare-api-token
