apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.43.0@sha256:5d4e1353927785744486fe317d263f442710ab5b27b1983aa1b719dfe2c665b6
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch
          envFrom:
            - secretRef:
                name: karakeep-secrets
            - configMapRef:
                name: karakeep-configuration
      volumes:
        - name: meilisearch
          persistentVolumeClaim:
            claimName: meilisearch-pvc
