apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.51.0@sha256:a9eb29ee09ab4943db3b4c68620bd6f3382e6b2b0ac4431c0e607b48dbcd4c14
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch
          envFrom:
            - secretRef:
                name: karakeep-secrets
            - configMapRef:
                name: karakeep-configuration
      volumes:
        - name: meilisearch
          emptyDir:
            sizeLimit: 500Mi
