apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.47.0@sha256:4931c0afd68b12d3db4a608268c6785bba26d3f3b43a228eff62ec38d5a47d8d
          env:
            - name: MEILI_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch
          envFrom:
            - secretRef:
                name: karakeep-secrets
            - configMapRef:
                name: karakeep-configuration
      volumes:
        - name: meilisearch
          persistentVolumeClaim:
            claimName: meilisearch-pvc
