apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--log.level=INFO"
      - "--api.dashboard=true"
    ports:
      web:
        exposedPort: 80
      websecure:
        exposedPort: 443
    service:
      spec:
        loadBalancerIP: "192.168.1.250"
