apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--log.level=INFO"
      - "--api.dashboard=true"
    ports:
      web:
        exposedPort: 80
      websecure:
        exposedPort: 443
    service:
      spec:
        loadBalancerIP: "192.168.1.250"
    certificatesResolvers:
      letsencrypt:
        acme:
          email: leehosanganson@gmail.com
          dnsChallenge:
            provider: cloudflare
            resolvers:
              - "1.1.1.1:53"
              - "8.8.8.8:53"
