apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-staging
  namespace: flux-system
spec:
  interval: 2m
  path: ./kubernetes/apps/overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
