apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-production
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/monitoring/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
