resources:
  - config.yaml
  - deployment.yaml
  - ingress.yaml
  - mariadb-deployment.yaml
  - mariadb-pvc.yaml
  - mariadb-service.yaml
  - pvc.yaml
  - secrets.yaml
  - service.yaml
labels:
  - pairs:
      app: grimmory
