#cloud-config
ssh_authorized_keys:
  - ssh-rsa <key>

package_update: true

packages:
  - git

runcmd:
 - '\curl -sfL https://get.k3s.io | INSTALL_K3S_CHANNEL="stable" K3S_TOKEN=$SERVER_TOKEN K3S_AGENT_TOKEN=$AGENT_TOKEN INSTALL_K3S_EXEC="server --cluster-init" K3S_KUBECONFIG_MODE=644 sh -'
