apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secrets-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: searxng-secrets
    creationPolicy: Owner
  data:
    - secretKey: SEARXNG_SECRET_KEY
      remoteRef:
        key: searxng-secret-key
