apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-rpc-secret-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: garage-rpc-credentials
    creationPolicy: Owner
  data:
    - secretKey: rpc-secret
      remoteRef:
        key: garage-rpc-secret
