log:
  level: info
runner:
  file: /data/.runner
  capacity: 1
  envs:
    DOCKER_HOST: tcp://localhost:2376
    DOCKER_TLS_VERIFY: "1"
    DOCKER_CERT_PATH: /certs/client
  timeout: 3h
  labels:
    - ubuntu-latest:docker://node:20-bookworm
container:
  network: host
  options: -v /certs/client:/certs/client
cache:
  enabled: true
