apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-reg-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: forgejo-runner-reg
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: forgejo-runner-registration-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-api-token-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: forgejo-runner-api-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: forgejo-runner-api-token
