apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |
    {
      "platform": "github",
      "repositories": [
        "leehosanganson/homelab"
      ],
      "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
      "onboarding": false,
      "requireConfig": "optional",
      "extends": [
        "config:recommended",
      ],
      "pinDigests": true,
      "prHourlyLimit": 0,
      "prConcurrentLimit": 0,
      "minimumReleaseAge": "7 days",
      "dependencyDashboard": true,
      "packageRules": [
        {
          "matchUpdateTypes": ["minor", "patch"],
          "automerge": true
        }
      ],
      "ignorePaths": [
        "fluxcd/clusters/production/flux-system/gotk-components.yaml",
        "kubernetes/infra/cloudnativepg/**",
        "kubernetes/infra/synology-csi/**"
      ],
      "flux": {
        "managerFilePatterns": [
          "^fluxcd/clusters/production/.+\\.ya?ml$",
        ]
      },
      "kubernetes": {
        "managerFilePatterns": [
          "^kubernetes/.+\\.ya?ml$/"
        ]
      }
    }
