apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          containers:
            - name: renovate
              image: ghcr.io/renovatebot/renovate:44.115.9@sha256:2327f790a2faf49aafc42cb3b5233f4f52b18fd3081c850f1adc17d2a9af584e
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              env:
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-env
                      key: token
                - name: RENOVATE_CONFIG_FILE
                  value: /usr/src/app/config.json
                - name: LOG_LEVEL
                  value: "debug"
              volumeMounts:
                - name: renovate-config
                  mountPath: /usr/src/app/config.json
                  subPath: config.json
          restartPolicy: Never
          volumes:
            - name: renovate-config
              configMap:
                name: renovate-config
