apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "0 */12 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          containers:
            - name: renovate
              image: ghcr.io/renovatebot/renovate:43.280.0@sha256:9be9e428913e773480477d71dd10b9a4f6ca12ed7328d148e2483283a43c2e90
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              env:
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-env
                      key: token
                - name: RENOVATE_CONFIG_FILE
                  value: /usr/src/app/config.json
                - name: LOG_LEVEL
                  value: "debug"
              volumeMounts:
                - name: renovate-config
                  mountPath: /usr/src/app/config.json
                  subPath: config.json
          restartPolicy: Never
          volumes:
            - name: renovate-config
              configMap:
                name: renovate-config
