apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: ghcr.io/renovatebot/renovate:43@sha256:6c503f53f84038135f4a721bccbc7fd95099e4c66e6db6e40171e41dd413defe
              env:
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-env
                      key: token
                - name: RENOVATE_CONFIG_FILE
                  value: /usr/src/app/config.json
                - name: LOG_LEVEL
                  value: "debug"
              volumeMounts:
                - name: renovate-config
                  mountPath: /usr/src/app/config.json
                  subPath: config.json
          restartPolicy: Never
          volumes:
            - name: renovate-config
              configMap:
                name: renovate-config
